apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name:  go_app1
          image: gotodengo89/go_app1
          ports:
            - containerPort: 6666
          env:
            - name: GREET
              valueFrom:
                configMapKeyRef:
                  name: app1-config
                  key: greeting
