apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name:  app1
          image: gotodengo89/go_app1
          ports:
            - containerPort: 7777
          volumeMounts:
          - mountPath: /config/
            name: app1-config-volume
            readOnly: true
      volumes:
      - name: app1-config-volume
        configMap:
          name: app1-config
          items:
          - key: config
            path: app1.yaml
